# Basic Release Workflow
# Triggers on release branch creation and commits to release branches

name: Release

on:
  create:
  push:
    branches:
      - 'release/**'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Semantic Versioning
        id: semver
        uses: major0/semver-release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Show Results
        run: |
          echo "Tag: ${{ steps.semver.outputs.tag }}"
          echo "Type: ${{ steps.semver.outputs.tag-type }}"
          echo "Major: ${{ steps.semver.outputs.major }}"
          echo "Minor: ${{ steps.semver.outputs.minor }}"
