# Basic Release Workflow
# Triggers on release branch creation and commits to release branches
#
# This example uses default prefixes:
#   - release-prefix: release/v (branches like release/v1.2)
#   - tag-prefix: v (tags like v1.2.0)
#
# For custom prefixes, see example/mono-repo.yml or configure:
#   with:
#     release-prefix: 'v'        # For branches like v1.2
#     tag-prefix: 'v'            # For tags like v1.2.0
# Note: Update branch triggers to match your release-prefix pattern

name: Release

on:
  create:
  push:
    branches:
      - 'release/**'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Semantic Versioning
        id: semver
        uses: major0/semver-release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # Custom prefix options (uncomment to use):
          # release-prefix: 'v'    # Short prefix for branches like v1.2
          # tag-prefix: 'v'        # Prefix for tags like v1.2.0

      - name: Show Results
        run: |
          echo "Tag: ${{ steps.semver.outputs.tag }}"
          echo "Type: ${{ steps.semver.outputs.tag-type }}"
          echo "Major: ${{ steps.semver.outputs.major }}"
          echo "Minor: ${{ steps.semver.outputs.minor }}"
