# Workflow Dispatch Example
# Manual testing with target-branch and dry-run inputs

name: Manual Release Test

on:
  workflow_dispatch:
    inputs:
      target-branch:
        description: 'Target release branch (e.g., release/v1.2)'
        required: true
        type: string
      dry-run:
        description: 'Simulate without creating tags'
        required: false
        type: boolean
        default: true
      debug:
        description: 'Enable debug logging'
        required: false
        type: boolean
        default: true

jobs:
  test-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Semantic Versioning
        id: semver
        uses: major0/semver-release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target-branch: ${{ inputs.target-branch }}
          dry-run: ${{ inputs.dry-run }}
          debug: ${{ inputs.debug }}

      - name: Show Results
        run: |
          echo "=== Semantic Versioning Results ==="
          echo "Tag: ${{ steps.semver.outputs.tag }}"
          echo "Type: ${{ steps.semver.outputs.tag-type }}"
          echo "Major: ${{ steps.semver.outputs.major }}"
          echo "Minor: ${{ steps.semver.outputs.minor }}"
          echo ""
          echo "Dry-run: ${{ inputs.dry-run }}"
          if [ "${{ inputs.dry-run }}" = "true" ]; then
            echo "No tags were created (dry-run mode)"
          fi
