name: 'Semantic Versioning Release Action'
description: 'Automates semantic versioning (SemVer 2.0.0) and release management for release branch workflows'
author: 'Your Name'

branding:
  icon: 'tag'
  color: 'blue'

inputs:
  token:
    description: 'GitHub token for API operations (tag creation, releases)'
    required: false
    default: ${{ github.token }}
  debug:
    description: 'Enable verbose debug logging'
    required: false
    default: 'false'
  dry-run:
    description: 'Simulate actions without creating tags'
    required: false
    default: 'false'
  target-branch:
    description: 'Target release branch for workflow_dispatch (e.g., release/v1.2)'
    required: false
    default: ''
  aliases:
    description: 'Create version alias tags (vX, vX.Y) for non-RC releases'
    required: false
    default: 'false'
  release-prefix:
    description: 'Prefix for release branch names, prepended to X.Y (e.g., release/v for release/v1.2)'
    required: false
    default: 'release/v'
  tag-prefix:
    description: 'Prefix for version tags and aliases, prepended to version (e.g., v for v1.2.0)'
    required: false
    default: 'v'

outputs:
  tag:
    description: 'The tag that was created or validated'
  tag-type:
    description: 'Type of tag: rc, patch, ga, or skipped'
  major:
    description: 'Major version number'
  minor:
    description: 'Minor version number'

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    INPUT_TOKEN: ${{ inputs.token }}
    INPUT_DEBUG: ${{ inputs.debug }}
    INPUT_DRY_RUN: ${{ inputs.dry-run }}
    INPUT_TARGET_BRANCH: ${{ inputs.target-branch }}
    INPUT_ALIASES: ${{ inputs.aliases }}
    INPUT_RELEASE_PREFIX: ${{ inputs.release-prefix }}
    INPUT_TAG_PREFIX: ${{ inputs.tag-prefix }}
